### ISSUE TITLE
Modularisation du code

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-plugin-qgis#180]
#### Objectifs

- [x]  Rendre le code plus facile à maintenir 

- [x]  Faciliter le passage à un fonctionnement asynchrone 

- [x] Effectuer des corrections

#### Futur dossier `modules` 

* Créer un sous-dossier `layers` qui contiendra les modules destinés à gérer **l'ajout de couche**. Cela consiste principalement à sortir la méthode *add_layer()* de la classe mère : 

  - [x] `add.py` : Ajout de couches (#178) 

  - [x] `md_sync.py` : Synchronisation des métadonnées (#209)

  - [x] `limitation_check.py` : Vérification des limitations

  **PR concernée(s) :**  #211

* Créer un sous-dossier `api` qui contiendra les modules destinés à gérer les **interactions avec l'api** Isogeo. Cela consiste principalement à sortir les méthode de requête à l'api Isogeo de la classe mère et à séparer l'actuel `api.py` en deux nouveaux modules : 

  - [x] `auth.py` : Gestion de l'authentification (formulaire, gestion du fichier...) (#177)

  - [x] `request.py` : Requêtes à l'api (token, ressources, url de requêtes...) (#177)

  - [x] `shares.py` : Partages alimentant l'application (mise en forme de la réponse à une requête sur les partages) (#177)

  **PR concernée(s) :** #213 , #216 

* Créer un sous-dossier `results` qui contiendra les modules destinés à **gérer l'affichage des résultats** dans le tableau. Cela consiste principalement à séparer l'actuel `results.py` en deux nouveaux modules : 

  - [x] `display.py` : Remplissage du tableau

  - [x] `cache.py` : Système de cache (#179)

  **PR concernée(s) :**  #212 
 
* Sortir la gestion des **recherches rapides** de la classe mère : 

  - [x] `quick_search.py` : Recherche rapide (édition, utilisation, stockage) (#176)

  **PR concernée(s) :**  #211 

* Sortir la **gestion des cases à cocher** de recherche de la classe mère : 

  - [x] `search_form.py` : Gestion des combo boxes (actualisation des champs et extraction des paramètres) (#210) 

  **PR concernée(s) :**  #217 

* Les modules `metadata_display.py` et `tools.py` resteront pratiquement inchangés.
